# Companhias administrativas

winter-solstice-description = Os três ramos da Federação dos Fuzileiros Trans-Solares ficam sob a direção do alto comando unificado da Federação, conhecido como Solstício de Inverno.


# Companhias centrais

drake-industries-description = Eficiência, lucros, confiabilidade. Drake Industries é uma antiga empresa de grande comércio que se transformou na maior gigante industrial do setor. Desde elegantes projetos de navios civis até refino de materiais, mantém-se à tona principalmente alimentando os conflitos ao redor. Oficialmente, desencoraja qualquer tipo de hostilidade cometida pelos membros da empresa. Promete lucros fáceis para todos os pilotos, engenheiros e seguranças privadas capazes dispostos a se alistarem sob sua bandeira. Não finja surpresa quando as condições de trabalho consistirem em prazos cortantes, sem pausas para banheiro e dormindo em um colchão sujo, porém.

steel-hammer-description = Conglomerado industrial massivo, e Companhia Central. Especializa-se no projeto, construção e equipamento de cascos de naves estelares empregados por civis, PMCs, ou o maior licitante, utilizando startups de base, aliados comerciais industriais estabelecidos e engenheiros de sistemas independentes terceirizados. Fornecedor principal de cascos e naves equipadas para o setor Colossus, tornando-a uma das espadas do conflito crescente entre as grandes facções disputando domínio. Após o colapso histórico da megacorporação Nanotrasen e os Aliados do Sindicato, subsidiárias de fabricação de cascos motivadas por lucro de ambos os lados perceberam que o melhor curso de ação era se separar o melhor possível dos poderes destruídos e começar de novo. SHM aceita projetos de todos os tipos de designers independentes (ou não) por todos os tipos de razões, desde melhorar o elenco de cascos universalmente disponíveis no mercado intergaláctico, até... contratos factionais extremamente valiosos. **Membros da Steel Hammer Manufacturing são geralmente construtores de navios, desmanteladores, designers ou mantenedores.**

harmony-medical-enterprises-description = Harmony Medical Enterprises é uma corporação baseada unicamente em práticas e suprimentos médicos, quando você é atingido no campo de batalha? A HME é a que forneceu aos seus superiores um acordo com desconto em canetas de combate e vários remédios que mantêm você na luta por mais tempo. Harmony Medical Enterprises são os principais fabricantes que promovem coisas como kits médicos, canetas de combate, estojos de medipen, equipamento médico, toda a tecnologia salva-vidas no setor. Embora não tenham domínio sobre a clonagem? Eles têm a próxima melhor coisa, medicina para os vivos.

midnight-arms-co-description = A Midnight Arms Company aproveitou uma galáxia recentemente refeita, uma que carecia e proibia mega-corporações em todas as capacidades. A Midnight Arms fornece armas para as massas independentes e várias outras corporações para o que precisarem delas, para o que são usadas, bem isso cabe àqueles que as compram. Armas são necessárias para todas as coisas nesta era, autodefesa, expedições, caça de recompensas. Todos são trabalhos que precisam de armas para realizá-los, MACo apenas se encontra como o principal fornecedor.

ussp-description = Os Remanescentes da USSP são os elementos sobreviventes da 78ª Frota Expedicionária e seu attached 13º Batalhão de Infantaria Naval. Uma vez encarregados de proteger o Setor Colossus sob a Operação Roundtable, a frota expedicionária foi despedaçada por uma ordem de retirada repentina e desorganizada, com grande parte perdida na retirada através das franjas distantes do setor. Cortados de seu lar distante e deixados sem mais ordens do Comando Naval da USSP, os sobreviventes agora resistem em isolamento. A Infantaria Naval, sobrecarregada por perdas sustentadas e liderança escassa, permanece uma força testada em batalha, mas cada vez mais tensa. Mantida unida pela camaradagem, orgulho e crença teimosa de que seu sacrifício ainda deve ter significado, os Remanescentes agora lutam para preservar o que resta, alguns mantendo a esperança de que um dia a União retornará, enquanto outros começam a duvidar que isso um dia acontecerá.

# Companhias maiores

dark-matter-enterprises-description = Das cinzas da Última Guerra Corporativa surgiu a Dark Matter Enterprises (DME), um farol de ambição pragmática em uma galáxia ainda reeling da paisagem interstellar devastada pela guerra criada pela ganância corporativa e diferenças ideológicas. Enquanto a TSF e a USSP lutavam pelo domínio galáctico, um coletivo de empreiteiros corporativos visionários viu um vácuo de poder deixado pela ausência dos antigos poderes que costumavam ser. Esses indivíduos forjaram a DME com um propósito singular: transcender as velhas maneiras controlando e melhorando o fluxo de conhecimento e recursos. Posicionando-se como indispensáveis para todos, mas sem dever a ninguém. Sua estrutura centralizada é uma resposta direta à fragmentação caótica de seus predecessores, garantindo tomadas de decisão ágeis e uma visão estratégica unificada.

aetherion-dynamics-description = Representando a vanguarda da inovação tecnológica, a Aetherion Dynamics é renomada por sua invenção do sistema de Lançamento e Projétil de Gás Comprimido (CGLP) usado na bateria de turbolaser Dymere ADEX-9, e armas inovadoras adicionais com pouca ou nenhuma filosofia de projeto consistente. Entre todas as suas famosas armas navais, eles iniciaram a Revolução de Artilharia na preparação para o conflito no Setor Colossus. Têm reputação como fabricantes e designers de alta qualidade, mais interessados em construir um produto eficaz do que em obter lucros.

horizon-energy-description = A líder na extração de gás, desde o valioso Plasma Prismático do monólito até os asteroides cheios de gás na borda externa do setor Colossus. Eles são os atuais líderes da indústria quando se trata do campo de extração e engenharia atmosférica. Eles fornecem serviços úteis tanto para mineiros novos e empreendedores quanto para os gaseiros veteranos e experientes. É bem provável que o ar que o espaçonauta comum respira e o rastro de gás que sua nave deixa para trás vieram da Horizon Energy.


# Companhias menores

universal-states-of-america-description = Os Estados Universais da América são um grupo de mercenários fanáticos que desejam trazer os valores dos antigos Estados Unidos para o século 25. Praticamente funcionam como um grupo de PMC, terceirizando milicianos patrióticos como mercenários, sob o nome de 'Vanguardas' para financiar seus sonhos de criar uma vasta e poderosa nação semelhante aos E.U.A., um sonho que muito provavelmente nunca realizarão. Mas, aos olhos deles, lógica e bom senso não são páreo para liberdade. Exerça seu direito à Segunda Emenda, grite com um chef porque ele chama suas batatas de "Batatas Espaciais" em vez de "Batatas da Liberdade", e deixe claro que você é um patriota universal amante de armas, defensor dos fracos, comedor de hambúrgueres, piloto espacial!

civil-defense-milita-description = Uma empresa relativamente nova fundada no Setor Colossus, a Milícia de Defesa Civil foi formada para proteger a população civil e seus interesses. Respondendo a indivíduos de alta patente decididos através de sua reputação, a milícia participa de atos de altruísmo, como defender pontos de interesse principais e manter cessar-fogos para que civis possam participar com segurança do comércio no sistema. O C.D.M. consiste em empreiteiros voluntários e mercenários e tem acesso apenas ao equipamento disponível para eles. Para o povo. Defender e não participar em atos sem sentido de violência. Você é o defensor daqueles que não podem se defender.

southern-peak-mercenaries-description = "Um bom rogue é um rogue morto." diz o slogan desta empresa mercenária vicious. Os Southern Peaks foram formados ao longo da fronteira espacial TSF-Rogue em retaliação contra piratas e insurgentes encroaching, em combinação com desconfiança total da TSFMC. Sem precisar de qualquer outra organização, TSP aims lutar de volta ao Setor Rogue por conta própria.

ullman-industries-description = Não é crime de guerra da primeira vez. Originalmente uma empresa básica no setor sem lei para produção de armas pequenas e produtos farmacêuticos, uma vez que a TSF chegou, a maioria das empresas foi para o setor público - registrando-se e cumprindo "práticas de trabalho seguras" e pagando aos empregados um "salário digno" - bem como processando líderes da empresa por acusações de "crimes de guerra". A Ullman Industries quebrou essa tendência permanecendo fiel às suas raízes como um elemento fringe, fornecendo armas, armaduras, navios, o que seja para todos e quaisquer clientes da Dinastia Phaetheon. A linha inferior é - se é ilegal no espaço da Federação, provavelmente é vendido pela Ullman Industries. O inferno, eles provavelmente são os que construíram.

nosske-eien-rnd-description = Renomados em outros setores por sua tecnologia de ponta e avanços, Nosske-Eien começou a se expandir e testar as águas no Setor Rogue contratando força de trabalho local, sejam civis regulares, pilotos ou mercenários, para a pesquisa sobre a xenoarqueologia local, xenobiologia e avanços tecnológicos. Nosske-Eien tem sido a principal fonte para os recentes avanços tecnológicos científicos e equipamentos, bem como equipamentos de mineração de asteroides de alta tecnologia e em breve, shuttlecraft. Embora, haja rumores de seus empreiteiros desaparecendo aleatoriamente de tempos em tempos, vamos torcer para que seja apenas um truque e nada para se preocupar, hein?

blackhawkpmc-description = O grupo de Contratação Militar Blackhawk (BMC) é um grupo mercenário premium operando no setor Colossus. Espera-se que os mercenários no grupo sejam treinados e profissionais. Eles executam tarefas mercenárias que variam desde proteção de ativos até assassinatos, mantendo sua reputação. O grupo é relativamente novo, criado por um grupo de mercenários independentes procurando construir um grupo mercenário poderoso. A partir de agora, as operações de recrutamento estão em ascensão. A Blackhawk PMC oferece uma variedade de serviços, desde fornecer segurança privada até assassinatos completos. Os mercenários Blackhawk vestem verde e frequentemente evitam chamar atenção para si mesmos. Lute com qualquer um por qualquer coisa para ganhar dinheiro.

# Grupos religiosos

zealots-of-balaam-description = Os Zealots e peregrinos de Balaam são luditas com extrema aversão ao uso de alta tecnologia e seres de alta tecnologia. Como seguidor de Balaam, trabalhe sob um zealot sênior ou um Bispo para ajudá-los a cobrar seus dízimos e realizar inspeções em busca de máquinas heréticas. Nunca ouça a blasfêmia das outras empresas. Destrua ou remova toda a tecnologia de escudos que encontrar, e pegue qualquer FTL usado por não crentes. Certifique-se de escolher seus alvos para essas ações com sabedoria, você frequentemente estará em inferioridade numérica. Saiba disso; Balaam ama nossas formas orgânicas, matar em massa convertentes em potencial não ajuda de nada os Bispos. Mantenha quaisquer orgânicos mortos no mínimo. Mas se eles recusarem você, e continuarem a abrigar máquinas heréticas, métodos mais fortes de persuasão podem provar úteis nos esquemas de Balaam.

cult-of-the-machine-god-description = A carne é fraca. Andar no caminho do Culto do Deus Máquina é rejeitar o caos da carne e abraçar a ordem divina da lógica. Os fiéis agem com precisão e propósito, nunca influenciados por emoção ou impulso. O avanço vem não através da paixão, mas através de melhoria calculada e disciplina inflexível. Aqueles que comandam no Culto o fazem através de clareza algorítmica, implantando operacionais Ascensionados com eficiência mecânica e espalhando influência através de Devotos ocultos ou Vasos errantes liderados por Techpriests. Seja aplicando doutrina em setores distantes ou executando domínio frio e estratégico, cada ação deve servir à grande equação. Em todas as coisas, a razão deve governar, e através dela, a vontade do Deus Máquina se manifesta...

The-Hive-description = Por que aperfeiçoar o antigo quando você pode se tornar algo novo? A Hive são cultistas que dedicam seu corpo ao caminho da supremacia evolutiva e às ordens da Rainha Mãe. Este é o lugar para aqueles que acreditam no progresso através da transformação, não importa quão monstruoso. Pureza genética é pecado, sempre procure se tornar uma versão melhor de si mesmo. Lembre-se que sua fé está na voz guia das Rainhas Mães, seguir outro é abandonar a colmeia. Sobrevivência do mais apto, se a Besta era fraca o suficiente para morrer por suas mãos, você pode colher seus órgãos como desejar.

# Companhias do mercado negro

paycheck-bratva-description = A Paycheck Bratva é uma rede de crime organizado originária do território da USSP, tendo se infiltrado no setor Colossus desde que a superpotência espacial se mudou para lá. É especializada principalmente no comércio de drogas de alto perfil, contrabando e roubos de grande impacto, junto com ataques a alvos com vários preços anexados. Além disso, operam em um código simplista: Sempre atire para matar se tiros forem disparados, nunca participe de drogas e muito menos das próprias, e mate aqueles que derramaram sangue da Paycheck Bratva. No geral, uma força intimidadora, vestidos com coletes kevlar, ternos e gravatas e balaclavas ou máscaras semelhantes, uma facção para thugs e ladrões profissionais de fato.

viper-group-description = Anteriormente uma empresa de corsários do Sindicato operando sob a asa do Gorlex com uma rígida doutrina militar, sua única missão designada era interromper as rotas de transporte interstelar ao longo das franjas do território da NT. Depois que a União dos Planetas Socialistas Soviéticos declarou sua independência da Confederação, o Viper Group viu uma oportunidade para explorar a situação da nação após a devastadora guerra corporativa e formou um escritório regional no espaço da USSP para facilitar operações locais contra a TSF sob o pretexto de "ajudar" na estabilização das fronteiras da USSP contra seus antigos senhores, ganhando reputação respeitável entre os primeiros escalões da USSP e lucro vendendo equipamento antigo da NT e do Sindicato saqueado para o governo da USSP e mercados negros locais. Pós-guerra corporativa, os Vipers migraram inteiramente para o espaço da USSP com uma fachada de PMC, afastando-se de ser associado publicamente com o militar da USSP e agindo independentemente. Com a USSP ficando contente com sua esfera de influência entre as estrelas após uma série de incursões devastadoras da TSF recuperando território da USSP, os Vipers deixaram seu domínio para rondar com sua melhor virtude; Ganância. Os Vipers expandiram seu alcance para áreas mais oportunísticas onde não se olharia duas vezes em sua direção ao pegar sua insígnia, como planetas fronteira desestabilizados e hubs espaciais de vários grupos de interesse, pois se tornaram notórios por realizar ataques em rotas de suprimento e transporte; mais notavelmente aqueles da TSF emergente e PD. Com a liderança frequentemente mudando de mãos violentamente uma vez que as presas de um comandante Viper ficam sem brilho, os Vipers são vistos como uma carta curinga cujo único interesse são créditos e cumprir contratos à letra. Relações favoráveis com o mercado negro do Colossus aceleraram sua chegada ao setor. Para aqueles que anseiam por perigo e riqueza, os Vipers não se curvam para ninguém; lealdade entrelaçada pela irmandade e presas expostas por créditos.

cerberus-surplus-provisions = O Cerberus Surplus Provisions, ou CSP, é um conglomerado de corretores, produtores e especialistas operando em diferentes divisões que foram recentemente elevados pela Dinastia Phaetheon, que o CSP apoia abertamente na invasão do Colossus. Seus constituintes trabalham juntos para lucro mútuo e para fortalecer a Dinastia. Seu MO é evitar conflitos, vender o que puderem e garantir que os "interesses comerciais" sejam representados no setor. Qualquer coisa pode ser comprada e vendida no setor Colossus, você só precisa de tática para realizar.

redsail-corsairs-description = Os RedSail Corsairs, ou RSC, são um grupo perigoso e influente de piratas e brigandius, que são publicamente conhecidos por se envolverem em atividades ilegais e violentas contra civis, autoridades e pessoal militar alike. Sua fonte de renda e especialização é sequestro, roubo de carga, tomada de reféns e assalto armado. Eles são marcados abertamente pelo Colossus Central como uma organização criminosa. Como um todo, os Corsairs funcionam como uma união entre invasores freebooting de todas as esferas da vida que juraram lealdade uns aos outros.
